### ISSUE TITLE
tty detection for mintty

### ISSUE THREAD

**Issue by BurntSushi** [softprops/atty#10]
Over time, ripgrep has grown its own tty detection code which includes a hack for (seemingly reliably) detecting the presence of a tty on Windows inside mintty. Would you be interested in a PR that brings it to this crate?

There isn't much code, but you can see it all here: https://github.com/BurntSushi/ripgrep/blob/master/src/atty.rs

There is a pretty long issue on the topic of mintty detection here, which includes the provenance of the hack: https://github.com/BurntSushi/ripgrep/issues/94 --- Spoiler alert: [it's what `git` does](https://github.com/git/git/blob/master/compat/winansi.c#L558-L560).

**Comment by softprops** [comment]
Absolutely! It never amazes me how complicated windows makes solving this seemingly simple problem
