### ISSUE TITLE
Documentation - Goal of the project 

### ISSUE THREAD

**Issue by ShalokShalom** [softprops/atty#43]
What is atty all about?

**Comment by BurntSushi** [comment]
As [the docs say](https://docs.rs/atty/0.2.14/atty/), this crate provides an API for determining whether stdin/stdout/stderr are connected to a tty or not. A "tty" is a [common abbreviation](https://en.wikipedia.org/wiki/Computer_terminal#Text_terminals) that indicates some kind of terminal that a user is interacting with, as opposed to a file or a network socket.

Knowing the answer to this question is often convenient for determining whether to emit colors or other kinds of graphics. You might want to do it on a tty, but almost certainly don't want to do it when writing to a file or a socket.

**Comment by ShalokShalom** [comment]
Ah, I read the Readme and the information is missing there. :)
You might wanna add it? 
Close this here, once it's convenient for you. :)
